telegram:
  bot:
    username: "tg_weather_bot"
    token: "7584345784:AAGCVM8VpR37Gi3KBR0GMdBwFzE60qLVEPc"

weather:
  api:
    key: "50256fba7831249df51e107b932a5b72"

geomagnetic:
  api:
    url: "https://services.swpc.noaa.gov/json/planetary_k_index_1m.json"

moon:
  api:
    app-id: "834e37e0-4f0f-40b0-b3e7-de6f44233f5c"
    app-secret: "f87b2f6dc7cbdabe1f90b72bcadf81a22ee759aae5ca4fcc3a5ec83b881decc3d85a7fa8a7f966eeba8b711754a5d04c2379c2c02bc1584dceea380b9b7c5a9481604a60323c4381e7b5325d44871c4bc1ea8d11568f8bd3ac041616394ffc8aca56236499cab6984e66dd5cab09c0c2"


logging:
  level:
    root: INFO
    com.telegrambot: DEBUG

spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: "update"
    database-platform: "org.hibernate.dialect.H2Dialect"

server:
  port: ${PORT:8080}

