name: Build TgWeatherBot and Deploy to Glitch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build project
      run: |
        ./gradlew clean build

    - name: Deploy to GitHub
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Build artifact updated by GitHub Actions" || echo "No changes to commit"
        git push origin master


    
